import type { VocabularyItem } from "../types/vocabulary.types";

export const dummyVocabularyItems: VocabularyItem[] = [
    // Japanese Greeting Vocabulary (section-002)
    {
        id: "vocab-001",
        section_id: "section-002",
        term: "おはよう",
        definition: "Good morning (casual)",
        example: "おはよう、元気？",
        pronunciation: "ohayou",
        audio_url: "/audio/ohayou.mp3",
        serial_number: 1,
        created_at: "2023-01-16T11:31:00Z",
        updated_at: "2023-01-16T11:31:00Z",
    },
    {
        id: "vocab-002",
        section_id: "section-002",
        term: "おはようございます",
        definition: "Good morning (formal)",
        example: "先生、おはようございます。",
        pronunciation: "ohayou gozaimasu",
        audio_url: "/audio/ohayou-gozaimasu.mp3",
        serial_number: 2,
        created_at: "2023-01-16T11:32:00Z",
        updated_at: "2023-01-16T11:32:00Z",
    },
    {
        id: "vocab-003",
        section_id: "section-002",
        term: "こんにちは",
        definition: "Good afternoon/Hello",
        example: "こんにちは、お元気ですか？",
        pronunciation: "konnichiwa",
        audio_url: "/audio/konnichiwa.mp3",
        serial_number: 3,
        created_at: "2023-01-16T11:33:00Z",
        updated_at: "2023-01-16T11:33:00Z",
    },
    {
        id: "vocab-004",
        section_id: "section-002",
        term: "こんばんは",
        definition: "Good evening",
        example: "こんばんは、いい夜ですね。",
        pronunciation: "konbanwa",
        audio_url: "/audio/konbanwa.mp3",
        serial_number: 4,
        created_at: "2023-01-16T11:34:00Z",
        updated_at: "2023-01-16T11:34:00Z",
    },
    {
        id: "vocab-005",
        section_id: "section-002",
        term: "さようなら",
        definition: "Goodbye",
        example: "さようなら、また明日。",
        pronunciation: "sayounara",
        audio_url: "/audio/sayounara.mp3",
        serial_number: 5,
        created_at: "2023-01-16T11:35:00Z",
        updated_at: "2023-01-16T11:35:00Z",
    },

    // Spanish Meeting People Vocabulary (section-007)
    {
        id: "vocab-006",
        section_id: "section-007",
        term: "Hola",
        definition: "Hello",
        example: "Hola, ¿cómo estás?",
        pronunciation: "OH-lah",
        audio_url: "/audio/hola.mp3",
        serial_number: 1,
        created_at: "2023-03-12T15:01:00Z",
        updated_at: "2023-03-12T15:01:00Z",
    },
    {
        id: "vocab-007",
        section_id: "section-007",
        term: "Buenos días",
        definition: "Good morning",
        example: "Buenos días, ¿cómo has dormido?",
        pronunciation: "BWAY-nohs DEE-ahs",
        audio_url: "/audio/buenos-dias.mp3",
        serial_number: 2,
        created_at: "2023-03-12T15:02:00Z",
        updated_at: "2023-03-12T15:02:00Z",
    },
    {
        id: "vocab-008",
        section_id: "section-007",
        term: "Buenas tardes",
        definition: "Good afternoon",
        example: "Buenas tardes, profesor.",
        pronunciation: "BWAY-nahs TAR-dehs",
        audio_url: "/audio/buenas-tardes.mp3",
        serial_number: 3,
        created_at: "2023-03-12T15:03:00Z",
        updated_at: "2023-03-12T15:03:00Z",
    },
    {
        id: "vocab-009",
        section_id: "section-007",
        term: "Buenas noches",
        definition: "Good evening/Good night",
        example: "Buenas noches, hasta mañana.",
        pronunciation: "BWAY-nahs NO-chehs",
        audio_url: "/audio/buenas-noches.mp3",
        serial_number: 4,
        created_at: "2023-03-12T15:04:00Z",
        updated_at: "2023-03-12T15:04:00Z",
    },
    {
        id: "vocab-010",
        section_id: "section-007",
        term: "Mucho gusto",
        definition: "Nice to meet you",
        example: "Hola, me llamo Ana. Mucho gusto.",
        pronunciation: "MOO-cho GOOS-toh",
        audio_url: "/audio/mucho-gusto.mp3",
        serial_number: 5,
        created_at: "2023-03-12T15:05:00Z",
        updated_at: "2023-03-12T15:05:00Z",
    },
];
